# Generated by Django 5.1.6 on 2025-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='description',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='title',
            field=models.CharField(default='Untitled Puzzle', max_length=255),
            preserve_default=False,
        ),
    ]
